#include "colmap_stuff.h"
#include <eigen3/Eigen/Geometry>
#include <filesystem>
#include <string>
#include <vector>
#include <stdexcept>
#include <assert.h>
#include "tag_image_solver.h"
/*
this version expects to have the text format files generated by colmap
loads transforms related to image
*/
std::vector<transform> getCameraTranforms(std::filesystem::path colmap_model_dir){
    
    std::string file = "images.txt";
    std::ifstream input_stream(colmap_model_dir / file );
    if (!input_stream.is_open()) {
        throw std::runtime_error("Failed to open " + file);
    }
    std::vector<transform> transforms;
    std::string in_str;
    while (getline(input_stream,in_str )) {
        if (in_str.front() == '#'){
            continue;
        }
        //#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
        // ja hyppy jokatoisen yli
        std::stringstream st(in_str);
        int f_id;
        double QW, QX, QY, QZ;
        double TX, TY, TZ;
        int c_id;
        std::string f_name;
        st >> 
        f_id >> QW >> QX>> QY>> QZ>> TX>> TY>> TZ >> c_id >> f_name;
        transforms.emplace_back(f_id, f_name ,Eigen::Quaterniond(QW,QX,QY,QZ),Eigen::Vector3d(TX,TY,TZ));
        getline(input_stream,in_str); // jump over
    }
    std::cout << "colmap model had " << transforms.size() << " images with transforms \n";
    return transforms;
}


// we asume just one camera for scene with id 1...
cameraParams getCameraParameters(std::filesystem::path colmap_model_dir){
    
    std::string file = "cameras.txt";
    std::ifstream input_stream(colmap_model_dir / file );
    if (!input_stream.is_open()) {
        throw std::runtime_error("Failed to open " + file);
    }
    Eigen::Matrix4d K ; // intrinsics
    Eigen::Vector4d distortion; 
    std::string in_str;
    while (getline(input_stream,in_str )) {
        if (in_str.front() == '#'){
            continue;
        }
        std::stringstream st(in_str);
        std::string model;
        int id,  width, height;
        double fx, fy, cx, cy, k1, k2, k3, k4;
        st >> id >> model >> width >> height >> fx >> fy >> cx >> cy >> k1 >> k2 >> k3 >> k4;
        std::cout << model;
        assert(model == "OPENCV"); // paremeters in file are different for different models.
        
        K << fx, 0, cx, 0,
        0,  fy, cy, 0,
        0,  0,  1, 0,
        0,  0,  0, 1;
        
        distortion << k1, k2, k3, k4;
        break;
    }
    std::cout << "intrinsics:\n " << K << "\n";
    //std::cout << "distortion:\n " << distortion << "\n";
    return cameraParams(K,distortion);
}

//The matrix.txt file is expected to contain scale qw qx qy qz tx ty tz and not the 4x4 transformation matrix. See Sim3d::FromFile.
// this is  the format expected by colmap model_transformer
void transToFile (Eigen::Quaterniond rotation, Eigen::Vector3d trans , float scale){
    std::string file =  name_prefix + "transformation.txt";
    std::ofstream out_stream(file);

    if (!out_stream.is_open()) {
        throw std::runtime_error("Failed to open " + file);
    }
    out_stream << std::setprecision(std::numeric_limits<double>::digits10 + 2);

    out_stream << scale << " " 
               << rotation.w() << " " 
               << rotation.x() << " " 
               << rotation.y() << " " 
               << rotation.z() << " " 
               << trans[0]    << " " 
               << trans[1]    << " " 
               << trans[2]    << "\n "; 
    std::cout << "wrote transform to file \n" << scale << "\n" << rotation << "\n" << translation << "\n";
}

// to produce output for colmap model_aligner;
void camerasTofile(std::vector<transform> cameras) {
    throw std::runtime_error("not implemented");
    return;
}
void camerasTofile(std::vector<matrixTransform> cameras){
    std::string file =  "camera_locations.txt";
    std::ofstream out(file);
    std::cout << "# " << cameras.size() << " cams outputed to " << file<< " \n";
    
    for(const auto& cam : cameras){
        assert(cam.filename != "");
        out << cam.filename << " " <<
            cam.derived_location.x() << " " << cam.derived_location.y() << " "<< cam.derived_location.z() << "\n";
    }

}

