#include "colmap_stuff.h"
#include <eigen3/Eigen/Geometry>
#include <filesystem>
#include <string>
#include <vector>
#include "tag_image_solver.h"
/*
this version expects to have the text format files generated by colmap
loads transforms related to image
*/
std::vector<transform> getCameraTranforms(std::filesystem::path colmap_model_dir){
    
    std::string file = "images.txt";
    std::ifstream input_stream(colmap_model_dir / file );
    if (!input_stream.is_open()) {
        throw std::runtime_error("Failed to open " + file);
    }
    std::vector<transform> transforms;
    std::string in_str;
    while (getline(input_stream,in_str )) {
        if (in_str.front() == '#'){
            continue;
        }
        //#   IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME
        // ja hyppy jokatoisen yli
        std::stringstream st(in_str);
        int f_id;
        double QW, QX, QY, QZ;
        double TX, TY, TZ;
        int c_id;
        std::string f_name;
        st >> 
        f_id >> QW >> QX>> QY>> QZ>> TX>> TY>> TZ >> c_id >> f_name;
        transforms.emplace_back(f_id, f_name ,Eigen::Quaterniond(QW,QX,QY,QZ),Eigen::Vector3d(TX,TY,TZ));
        getline(input_stream,in_str); // jump over
    }
    std::cout << "colmap model had " << transforms.size() << " images with transforms \n";
    return transforms;

}

// we asume just one camera for scene with id 1...
cameraParams getCameraParameters(std::filesystem::path colmap_model_dir){
    
    std::string file = "cameras.txt";
    std::ifstream input_stream(colmap_model_dir / file );
    if (!input_stream.is_open()) {
        throw std::runtime_error("Failed to open " + file);
    }
    Eigen::Matrix4d K ; // instricsts
    Eigen::Vector4d distortion; 
    std::string in_str;
    while (getline(input_stream,in_str )) {
        if (in_str.front() == '#'){
            continue;
        }
        std::stringstream st(in_str);
        std::string line, dummy;
        int width, height;
        double fx, fy, cx, cy, k1, k2, k3, k4;

        st >> dummy >> width >> height >> fx >> fy >> cx >> cy >> k1 >> k2 >> k3 >> k4;
        K << fx, 0, cx, 0,
            0,  fy, cy, 0,
            0,  0,  1, 0,
            0,  0,  0, 1;

        distortion << k1, k2, k3, k4;
        break;
                
    }
    return cameraParams(K,distortion);
}
